env: "development"
host: "http://loogle.org"

#邮件通知
email_account: "kooglemail@qq.com"
email_password: "shkybvxhnvamdgia"
email_stmp_port: "587"
email_stmp_address: "smtp.qq.com"

#Mail 接收管理
pop_host: "pop.gmail.com"
pop_username: "koogle.zhang@gmail.com"
pop_password: "twggmkcbwamsyddk"

#消息通知
default_mobile: "18211109527"
wechat_group_key: "3969-7430d6c874dc6c071f4a20d1d92b4935"
dingding_bot: "62440bdb94c167c7d5a2b8a2224e3da11cbcc95d1facef14a8b34f4c763d7819"
trading_bot : "1032815700f0c1bdbfd94721f88dabb449558260abf763a151a26c1123f244d7"
yunpian_key: "5281a1f15da352c1e13f834a0ec0203b"
yunpian_tpl: "1950240"

#交易所通信
bittrex_key: "f8592d2fb9cc4d39967afa612190bfd3"
bittrex_secret: "7054971638a74cdc89e7e6cd96e784bd"

# koogle.zhang@gmail.com
# binance_key: "o5jXtugDWJLwsalNvXjvhhLc0MGS8ukZ9Vx306KocwCriFLbtj6BvaOyPEhoSzJ2"
# binance_secret: "SpDIu6Maek5w5aIL1gJdnZKhi2NTSP6ohb6C6Zll6kaZkxQHI0nAhPQOX8yejiP2"

#王超 Binance
# 7FfPKIYCODT3ZySqokuGc0xowgSezwj0IjJ6MWvFSAFehsIrzjdb56XPnp9tmZRZ
# B77p9NqulhCfT32uSP6A0RPSHg1Yz8p1Q4IY3DEsMjdRaZ2srWaCNosP6aAMtv9W

# c9ab44805bd227e2121862e0ab7033ea
# 0cfdd6152c802c3b6d179fd4d2f4995b00aad106d29ecca51dfde5aabf14c5db

# kooglezhang@gmail.com
binance_key: "IMJMUNzDldjXZdyiPqHKzjYMdMLBGtA5laxCkuLcx2solBZWcKDjnIeEy0I1nDyu"
binance_secret: "TzUj0jL755Su7ePLdV2ibXy7YSGkCrcPoimZwe3zYmAJojbcXQuTglZHPYIOgmf8"

# koogle.zhang@gmail.com
# future_key: "e5ccVD9INU01FZg0vbevTqVPX6CXCLlKFS3rhP4v66arD3dL1A8zaP1zY1TUUVlk"
# future_secret: "OZGQ7OTz16yYAnMUCY6OnhOzSPcEdanmLKdzq4zwwgDAr0wWXRuGzE4rLAJvgt1f"

# kooglezhang@gmail.com
future_key: "G12gWVeSADGhJamAaetucFH022ZleTt06ILtnj6TnjiQRJ4eLjaoCNaDip8o8fy5"
future_secret: "tzxwcBKGtaWOuRs7GLMvmcIqqb2ryLa6L42WJWvx2sI3v7JeVzZ6fOWPdQZoajPU"

daemon_cn: {'takeprofit': '止盈保收', 'stoploss': '止损保本', 'chasedown': '逐仓加码', 'fastrade': '高频精灵', 'fluctuation': '每日涨跌'}
fluctuation_future: true
fluctuation_binance: false